import requests
import os
import sys
import time
from datetime import datetime
from pathlib import Path

# OpenRouter API configuration
API_URL = "https://openrouter.ai/api/v1/chat/completions"
API_KEY = os.environ.get("API_KEY", "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")

# Reliable Free Models for Financial Analysis
FREE_MODELS = {
    "1": {"name": "meta-llama/llama-3.2-3b-instruct:free", "desc": "Llama 3.2 3B - Best for card comparisons"},
    "2": {"name": "google/gemma-2-9b-it:free", "desc": "Gemma 2 9B - Great for reward analysis"},
    "3": {"name": "qwen/qwen-2.5-7b-instruct:free", "desc": "Qwen 2.5 7B - Excellent for calculations"},
    "4": {"name": "mistralai/mistral-7b-instruct:free", "desc": "Mistral 7B - Best for financial advice"},
    "5": {"name": "microsoft/phi-3-mini-128k-instruct:free", "desc": "Phi-3 Mini - Good for detailed reports"},
}

FALLBACK_MODELS = [
    "meta-llama/llama-3.2-3b-instruct:free",
    "google/gemma-2-9b-it:free",
    "mistralai/mistral-7b-instruct:free",
    "qwen/qwen-2.5-7b-instruct:free",
]

def generate_content(prompt: str, model: str = "meta-llama/llama-3.2-3b-instruct:free", retry_fallback: bool = True) -> dict:
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/starkarthikr/credit-card-optimizer",
        "X-Title": "Credit Card Optimizer"
    }
    
    models_to_try = [model]
    if retry_fallback:
        for fallback in FALLBACK_MODELS:
            if fallback != model and fallback not in models_to_try:
                models_to_try.append(fallback)
    
    for attempt, current_model in enumerate(models_to_try, 1):
        try:
            print(f"\n💳 Analyzing credit cards... (Attempt {attempt}/{len(models_to_try)})")
            print(f"   Model: {current_model}")
            print(f"   Query: {prompt[:100]}..." if len(prompt) > 100 else f"   Query: {prompt}")
            
            payload = {
                "model": current_model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.7,
                "max_tokens": 2000
            }
            
            response = requests.post(API_URL, json=payload, headers=headers, timeout=90)
            
            if response.status_code == 429:
                print(f"\n⚠️ Rate limited on {current_model}")
                if attempt < len(models_to_try):
                    print(f"   Retrying with fallback model...")
                    time.sleep(2)
                    continue
                else:
                    return {"success": False, "content": "", "error": "All models rate limited", "model_used": None}
            
            if response.status_code != 200:
                error_msg = f"HTTP {response.status_code}: {response.text}"
                print(f"\n❌ API Error: {error_msg}")
                if attempt < len(models_to_try):
                    print(f"   Trying fallback model...")
                    time.sleep(1)
                    continue
                return {"success": False, "content": "", "error": error_msg, "model_used": None}
            
            data = response.json()
            content = data["choices"][0]["message"]["content"]
            
            print(f"\n✅ Analysis complete! Generated {len(content)} characters.")
            if attempt > 1:
                print(f"   🔄 Used fallback model after {attempt-1} attempt(s)")
            print()
            
            return {"success": True, "content": content, "error": None, "model_used": current_model}
            
        except Exception as e:
            error_msg = f"Exception: {str(e)}"
            print(f"\n❌ Error: {error_msg}")
            if attempt < len(models_to_try):
                print(f"   Trying fallback model...")
                time.sleep(1)
                continue
            return {"success": False, "content": "", "error": error_msg, "model_used": None}
    
    return {"success": False, "content": "", "error": "All retry attempts failed", "model_used": None}

def save_output(prompt: str, content: str, model: str) -> str:
    output_dir = Path("recommendations")
    output_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"{timestamp}-card-analysis.md"
    filepath = output_dir / filename
    
    markdown_content = f"""# Credit Card Analysis Report

**Generated:** {datetime.now().strftime("%B %d, %Y at %I:%M %p IST")}
**AI Model:** `{model}`
**Report Type:** Personalized Card Optimization

---

## Query

{prompt}

---

## Recommendations

{content}

---

*Generated by [Credit Card Optimizer](https://github.com/starkarthikr/credit-card-optimizer)*  
*Powered by [OpenRouter AI](https://openrouter.ai) - 100% FREE financial intelligence*
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    return str(filepath)

def update_index():
    output_dir = Path("recommendations")
    if not output_dir.exists():
        return
    
    files = [f for f in output_dir.glob("*.md") if f.name != "INDEX.md"]
    files = sorted(files, reverse=True)
    
    if not files:
        return
    
    index_content = f"""# Credit Card Analysis Index

**Last Updated:** {datetime.now().strftime("%B %d, %Y at %I:%M %p IST")}
**Total Analyses:** {len(files)}

---

## All Card Recommendations

"""
    
    for file in files:
        date_str = file.stem.replace('-card-analysis', '')
        try:
            date_obj = datetime.strptime(date_str, "%Y-%m-%d_%H-%M-%S")
            formatted_date = date_obj.strftime("%B %d, %Y at %I:%M %p")
        except:
            formatted_date = date_str
        
        index_content += f"- [{formatted_date}]({file.name})\n"
    
    with open(output_dir / "INDEX.md", 'w', encoding='utf-8') as f:
        f.write(index_content)
    
    print(f"\n📄 Index updated: recommendations/INDEX.md ({len(files)} reports)")

if __name__ == "__main__":
    print("=" * 80)
    print("    💳 CREDIT CARD OPTIMIZER - AI-POWERED RECOMMENDATIONS 💳")
    print("=" * 80)
    
    is_github_actions = os.environ.get('GITHUB_ACTIONS') == 'true'
    custom_prompt = os.environ.get('CUSTOM_PROMPT', '')
    custom_model = os.environ.get('CUSTOM_MODEL', 'meta-llama/llama-3.2-3b-instruct:free')
    
    if is_github_actions and custom_prompt:
        print("\n🤖 Running automated card analysis")
        prompts = [custom_prompt]
        model = custom_model
    elif not is_github_actions:
        print("\n💻 Running in interactive mode\n")
        
        use_custom = input("Use custom card analysis query? (y/n): ").strip().lower()
        
        if use_custom == 'y':
            user_prompt = input("\nEnter your credit card query: ")
            prompts = [user_prompt]
        else:
            prompts = [
                "Compare the top 5 Indian credit cards for travel rewards in 2025, including earning rates, redemption value, annual fees, and lounge access benefits",
                "Analyze the best credit cards for online shopping in India with cashback percentages, partner merchants, annual fee vs benefits analysis",
                "Create a comprehensive guide for credit card reward optimization strategies including milestone benefits, accelerated rewards, and annual value calculation"
            ]
        
        print("\n" + "="*80)
        print("💳 AVAILABLE AI MODELS FOR CARD ANALYSIS")
        print("="*80)
        for key, model_info in FREE_MODELS.items():
            print(f"{key:>2}. {model_info['desc']}")
        print("="*80)
        
        model_choice = input("\nSelect model (1-5, default=1): ").strip() or "1"
        model = FREE_MODELS.get(model_choice, FREE_MODELS["1"])["name"]
        
    else:
        print("\n⏰ Running scheduled card optimization")
        prompts = [
            "Generate a monthly credit card optimization report for December 2025 covering best new card launches, devaluation alerts, limited-time offers, and spending category recommendations",
            "Analyze the latest credit card fee changes, reward program updates, and benefit modifications across major Indian banks",
            "Create a comprehensive credit card portfolio strategy for maximizing rewards across different spending categories"
        ]
        model = custom_model
    
    print(f"\n💳 Generating {len(prompts)} card analysis report(s)...")
    print(f"🎯 Primary Model: {model}")
    print(f"🔄 Auto-fallback enabled")
    print("="*80)
    
    success_count = 0
    
    for i, prompt in enumerate(prompts, 1):
        print(f"\n\n{'='*80}")
        print(f"[CARD ANALYSIS #{i} of {len(prompts)}]")
        print(f"{'='*80}")
        print(f"\n💳 Query: {prompt}\n")
        
        result = generate_content(prompt, model, retry_fallback=True)
        
        if result['success']:
            print("\n" + "-" * 80)
            print("💰 CARD RECOMMENDATIONS:")
            print("-" * 80)
            print(result['content'])
            print("-" * 80)
            
            filepath = save_output(prompt, result['content'], result['model_used'])
            print(f"\n✅ Report saved: {filepath}")
            success_count += 1
        else:
            print(f"\n❌ Failed to generate analysis: {result['error']}")
    
    if success_count > 0:
        update_index()
    
    print("\n" + "="*80)
    print(f"\n🎉 COMPLETE! Successfully generated {success_count}/{len(prompts)} reports.")
    print(f"\n📂 Check the 'recommendations/' folder for analyses.")
    print(f"📊 View index: recommendations/INDEX.md")
    print(f"\n💳 100% FREE AI-powered credit card intelligence!\n")
    print("="*80)
